apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: restaurante-app-hpa
  namespace: restaurante-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: restaurante-app
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
