apiVersion: v1
kind: Service
metadata:
  name: restaurante-app
  namespace: restaurante-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: restaurante-app
