version: '3.1'
services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - MONGODB_CONNECTION_STRING=mongodb://database:27017
#    depends_on:
#      - mongodb
  database:
    image: mongo:4.4
    ports:
      - "27017:27017"
