name: Deploy Kubernetes

on:
  workflow_run:
    workflows: ["Validar e publicar imagem."]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install and configure kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configurando credenciais AWS para kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name tech-challenge-cluster-restaurante

      - name: Conferindo se namespace existe e criando caso não
        run: |
          if ! kubectl get namespace restaurante-app > /dev/null 2>&1; then
            kubectl create namespace restaurante-app
          fi

      - name: Atualizando Deployment com a nova tag da imagem Docker
        run: |
          IMAGE_TAG=${{ github.event.workflow_run.outputs.image_tag }}
          sed -i "s|<IMAGE_TAG>|$IMAGE_TAG|g" ./kubernetes/application/Deployment.yaml

      - name: Aplicando as alterações no Kubernetes
        run: |
          kubectl apply -f ./kubernetes/application/Service.yaml
          kubectl apply -f ./kubernetes/application/Deployment.yaml
          kubectl apply -f ./kubernetes/application/hpa.yaml
